[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ["npm install --no-cache"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/npm-cache"